// Generated by CoffeeScript 1.10.0
(function() {
  angular.module("newsletter").run(["$rootScope", "$location", "Auth", "Config", "restAPI", function($rootScope, $location, Auth, Config, restAPI) {}]);

}).call(this);
