// Generated by CoffeeScript 1.10.0
(function() {
  angular.module("newsletter").service("Auth", [
    "$cookies", function($cookies) {
      this.setToken = function(token) {
        return $cookies.put("token", token);
      };
      this.getToken = function() {
        return $cookies.get("token");
      };
      this.setOpenId = function(open_id) {
        return $cookies.put("open_id", open_id);
      };
      this.getOpenId = function() {
        return $cookies.get("open_id");
      };
      this.cleanAuth = function() {
        $cookies.remove("token");
        return $cookies.remove("open_id");
      };
      return this;
    }
  ]);

}).call(this);
