// Generated by CoffeeScript 1.10.0
(function() {
  angular.module("newsletter").factory("interceptor", [
    "$q", "$location", "Auth", "Config", function($q, $location, Auth, Config) {
      return {
        request: function(request) {
          request.headers = request.headers || {};
          if (Auth.getToken()) {
            request.headers.Authorization = Auth.getToken();
          }
          return request;
        },
        response: function(response) {
          return response || $q.when(response);
        },
        responseError: function(rejection) {
          if (rejection.status === 401) {
            $location.path('/auth');
          }
          return $q.reject(rejection);
        }
      };
    }
  ]).config([
    "$httpProvider", function($httpProvider) {
      return $httpProvider.interceptors.push("interceptor");
    }
  ]);

}).call(this);
