// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('newsletter').factory('restAPI', function($resource, Config) {
    var api, auth_api;
    api = Config.api;
    auth_api = Config.auth_api;
    return {
      profile: (function() {
        return $resource(api + "/profile");
      })(),
      posts: (function() {
        return $resource(api + "/posts/:post_id");
      })(),
      mail: (function() {
        return $resource(api + "/posts/:post_id/mail");
      })(),
      mailTest: (function() {
        return $resource(api + "/posts/:post_id/mail_test");
      })(),
      memberRoles: (function() {
        return $resource(api + "/member_roles");
      })(),
      ext_token: (function() {
        return $resource(auth_api + "/ext_token/:open_id");
      })(),
      sup_auth: (function() {
        return $resource(auth_api + "/sup_auth");
      })(),
      token_check: (function() {
        return $resource(auth_api + "/token_check");
      })()
    };
  });

}).call(this);
