// Generated by CoffeeScript 1.10.0
(function() {
  angular.module("newsletter").controller("postsCtrl", [
    "$rootScope", "$scope", "$route", "$location", "restAPI", function($rootScope, $scope, $route, $location, restAPI) {
      $scope.posts = restAPI.posts.query();
      return $scope.open_post = function(post_id) {
        return $location.path("/edit_post/" + post_id);
      };
    }
  ]);

}).call(this);
