// Generated by CoffeeScript 1.10.0
(function() {
  angular.module("newsletter").controller("profileCtrl", [
    "$scope", "restAPI", function($scope, restAPI) {
      $scope.profile = restAPI.profile.get();
      return $scope.update_profile = function() {
        console.log('update');
        console.log($scope.profile);
        return $scope.profile.$save();
      };
    }
  ]);

}).call(this);
